[package]

name = "rusttol"
version = "0.0.1"
authors = [ "vycb <vycb777@gmail.com>" ]

[[bin]]
name = "rusttol"

[dependencies]
xml-rs = "*"
log = "*"
time = "*"
env_logger = "*"
rusqlite = "*"